[project]
name = "nb-ibp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy==2.1.0",
    "scanpy>=1.11.2",
    "scikit-misc>=0.5.1",
    "scipy>=1.16.0",
    "tqdm>=4.67.1",
]
